### ISSUE TITLE
Remove "Add environment path" for a default installation

### ISSUE THREAD

**Issue by thom8** [alexdesignworks/dcr#13]
Updating the `PATH` automatically can affect other projects and it's more common that a project will just have instructions to add itself to the path or assume a global installation in which the composer bin has already been added to the `PATH`.

At the moment it makes it difficult to integrate into a project when you don't want the `.profile` file modified and don't need the bin directory added to the `PATH`.

Rather than needing to `source ~/.profile` in the current session you could directly add the local projects bin to the `PATH` in the current session -- `export PATH=/path/to/project/bin:$PATH` or just call the bin directly - `vendor/bin/dcr`

**Comment by thom8** [comment]
Just to provide an example it you have 2 projects installed with different versions of drush (installed as a composer dependency) only one of these projects can be added to the global `PATH` at a time as drush would always use the version of the project that was included in the global `PATH` rather than a projects local version of possibly the globally installed version.

**Comment by alexdesignworks** [comment]
I will add automated adding to path as an option of installation. By default it will not modify PATH in `.profile` anymore.

**Comment by thom8** [comment]
If you're going to keep it please add a condition around the line in the case the composer bin directory is moved or deleted and perhaps append the PATH rather than prepend as this could cause some issues, especially if you're always assuming the local version of phpcs/phpcbf when using composer.

**Comment by christopher-hopper** [comment]
Changes to the `PATH` placed in the `~/.profile` file during install do not take effect until I Log-out of my machine and log back in again. I'm using Ubuntu 14.04 LTS as my desktop OS.

The `~/.profile` file is normally only executed for log-in shells. So until I log-out and back in after installing dcr, this `PATH` change in `~/.profile` isn't seen.

If you're wanting this to work a bit more consistently and predictably across more than just a MacOS I'd suggest making `PATH` environment variable changes in `~/.bashrc` which is executed for bash interactive shells. 

For more information see the [Bash Startup Files](https://www.gnu.org/software/bash/manual/html_node/Bash-Startup-Files.html#Bash-Startup-Files) section of the GNU bash manual for more information on the order of precedence and invocation rules for typical shell startup files.
