### ISSUE TITLE
Always use the project version of `phpcs` & `phpcbf`

### ISSUE THREAD

**Issue by thom8** [alexdesignworks/dcr#16]
https://github.com/alexdesignworks/dcr/blob/99fd8d6b9e4cbada8481dc7ce84f170ad3bc70ee/dcr#L88-L89

Rather than using `which` we should always use the local project version of `phpcs` & `phpcbf` as there could be version differences between projects and `which` will always pick up the global reference.

**Comment by alexdesignworks** [comment]
could you please advise how to do this better? if phpcs was installed with composer outside of DCR, the path to phpcs binary may be different than `vendor/bin/phpcs`.

**Comment by thom8** [comment]
Maybe fallback to which if a local bin can't be found, will take a look
tomorrow

**Comment by thom8** [comment]
@alexdesignworks you could check for the existence of the local binaries.

```
if [ -f "$(get_composer_bin_dir)/phpcs" ] ; then
  local command_phpcs="$(get_composer_bin_dir)/phpcs"
else
  local command_phpcs=$(which phpcs)
fi
```

**Comment by alexdesignworks** [comment]
Implemented
