### ISSUE TITLE
How to exclude a rule?

### ISSUE THREAD

**Issue by Johnzzon** [alexdesignworks/dcr#29]
I'm trying to get a specific project to exclude one rule, namely `Drupal.Semantics.ConstantName.ConstantStart`, but I can't figure out how to do it.
I believe the App ruleset in the project .dcr-folder is the correct place. I've tried adding the following in there but it doesn't seem to do anything.

```
<rule ref="Drupal">
    <exclude name="Drupal.Semantics.ConstantName.ConstantStart" />
</rule>
```

Could you instruct me on how to exclude a specific rule like this?

**Comment by alexdesignworks** [comment]
@Johnzzon 
Once `dcr` is initialised for your project, a `.dcr/App/ruleset.xml` will be copied to your project root. 

Within that file, use the following snippet to exclude your files:

```
<?xml version="1.0"?>
<ruleset name="App">

<!-- some other rules here ->

  <!--Allow constants to not start with module's prefix.-->
  <rule ref="Drupal.Semantics.ConstantName.ConstantStart">
    <exclude-pattern>*</exclude-pattern>
  </rule>
</ruleset>
```

**Comment by Johnzzon** [comment]
Thank you very much! Worked like a charm :)
