### ISSUE TITLE
dcr fix converts array() to []

### ISSUE THREAD

**Issue by ivrh** [alexdesignworks/dcr#6]
At the moment `dcr` with `fix` applied converts all PHP arrays from array() notation to []. Is there a way to configure it not to?

E.g. `array('a' => 'b')` becomes `['a' => 'b']`

**Comment by alexdesignworks** [comment]
Yes, this a short array syntax that all PHP projects should use since PHP 5.4

You can add this to your `dcr_standards/ruleset.xml` directory:
```
  <rule ref="Generic.Arrays.DisallowLongArraySyntax.Found">
    <exclude-pattern>*</exclude-pattern>
  </rule>
```
