### ISSUE TITLE
Add quiet flag to dcr init

### ISSUE THREAD

**Issue by Decipher** [alexdesignworks/dcr#7]
In DCIR (https://github.com/Decipher/dcir) I am using DCR to run the code review tests, but as the projects using DCIR are unlikely to have DCR config present I need to run `dcr init` during run time. As such, it would be ideal if I could quiet or suppress the output of the install function as it's not relevant to the test results.

**Comment by alexdesignworks** [comment]
`--quiet` flagg was added to `dcr init`, `dcr install` and `dcr` commands to suppress all output and rely only on exit code + tests.

Implemented in https://github.com/alexdesignworks/dcr/pull/9

**Comment by Decipher** [comment]
FYI, and I don't know if this is intentional, but it appears that the flag has to be straight after the `dcr` command to work, e.g., `dcr --quiet init` works, but `dcr init --quiet` doesn't work.

Otherwise, thanks for the quick turnaround on this, greatly appreciated.
