### ISSUE TITLE
Add flag to suppress/specify success message.

### ISSUE THREAD

**Issue by Decipher** [alexdesignworks/dcr#8]
Currently if DCR is successful it spits out `All good! You're awesome!`, it would be ideal if I could prevent this message or alter this message.

**Comment by Decipher** [comment]
Also good to be able to do the same for the error message.

**Comment by alexdesignworks** [comment]
Suppression is implemented with `--no-messages` option.
Specific message text can be specified in `.dcr.yml`.

https://github.com/alexdesignworks/dcr/pull/9
